# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 《计算传播基础》
author: Cheng-Jun Wang
logo: ./img/logo/Socratessee.gif

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

exclude_patterns: [pattern1/*, README.md, deploy.sh, LICENSE]

parse:
  myst_extended_syntax: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/chengjun/mybook  # Online location of your book
  path_to_book: /  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  comments:
    hypothesis: true
