name: Deploy to gh-pages
# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository
# When you use deploy_key, set your private key to the repository which includes this action
# and set your public key to your external repository.
# https://github.com/wowchemy/wowchemy-hugo-modules/issues/2240

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
  
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # - uses: pre-commit/action@v2.0.0
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U jupyter-book
        
    - name: Build
      run: | 
        jupyter-book build .
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
      
